name: camera_frame
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_bloc: ^0.4.0
  json_annotation: ^2.0.0
  meta: ^1.1.7
  web_socket_channel: ^1.0.9

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  json_serializable: ^2.0.2
  pedantic: ^1.0.0
  sass_builder: ^2.1.2
  test: ^1.5.1
